package com.vishnu.campalette.ui.theme

import androidx.compose.ui.graphics.Color

val AtelierPrimary = Color(0xFF004743)
val AtelierOnPrimary = Color(0xFFFFFFFF)
val AtelierPrimaryContainer = Color(0xFF1F5F5B)
val AtelierOnPrimaryContainer = Color(0xFF99D7D1)
val AtelierPrimaryFixed = Color(0xFFB0EEE8)
val AtelierPrimaryFixedDim = Color(0xFF95D2CC)
val AtelierInversePrimary = Color(0xFF95D2CC)

val AtelierSecondary = Color(0xFF81542E)
val AtelierOnSecondary = Color(0xFFFFFFFF)
val AtelierSecondaryContainer = Color(0xFFFEC394)
val AtelierOnSecondaryContainer = Color(0xFF794E29)
val AtelierSecondaryFixed = Color(0xFFFFDCC3)
val AtelierSecondaryFixedDim = Color(0xFFF5BB8C)

val AtelierTertiary = Color(0xFF18481A)
val AtelierOnTertiary = Color(0xFFFFFFFF)
val AtelierTertiaryContainer = Color(0xFF31602F)
val AtelierOnTertiaryContainer = Color(0xFFA3D99B)
val AtelierTertiaryFixed = Color(0xFFBAF1B1)
val AtelierTertiaryFixedDim = Color(0xFF9FD497)

val AtelierSurface = Color(0xFFFDF9F4)
val AtelierSurfaceBright = Color(0xFFFDF9F4)
val AtelierSurfaceDim = Color(0xFFDDD9D5)
val AtelierSurfaceVariant = Color(0xFFE6E2DD)
val AtelierSurfaceContainerLowest = Color(0xFFFFFFFF)
val AtelierSurfaceContainerLow = Color(0xFFF7F3EE)
val AtelierSurfaceContainer = Color(0xFFF1EDE8)
val AtelierSurfaceContainerHigh = Color(0xFFEBE8E3)
val AtelierSurfaceContainerHighest = Color(0xFFE6E2DD)

val AtelierBackground = Color(0xFFFDF9F4)
val AtelierOnBackground = Color(0xFF1C1C19)
val AtelierOnSurface = Color(0xFF1C1C19)
val AtelierOnSurfaceVariant = Color(0xFF3F4947)
val AtelierInverseSurface = Color(0xFF31302D)
val AtelierInverseOnSurface = Color(0xFFF4F0EB)

val AtelierOutline = Color(0xFF6F7978)
val AtelierOutlineVariant = Color(0xFFBFC8C7)
val AtelierSurfaceTint = Color(0xFF2A6864)

val AtelierError = Color(0xFFBA1A1A)
val AtelierOnError = Color(0xFFFFFFFF)
val AtelierErrorContainer = Color(0xFFFFDAD6)
val AtelierOnErrorContainer = Color(0xFF93000A)

val AtelierDarkPrimary = Color(0xFF7CD4CE)
val AtelierDarkOnPrimary = Color(0xFF003733)
val AtelierDarkPrimaryContainer = Color(0xFF004F4A)
val AtelierDarkOnPrimaryContainer = Color(0xFF99D7D1)
val AtelierDarkPrimaryFixed = Color(0xFFB0EEE8)
val AtelierDarkPrimaryFixedDim = Color(0xFF95D2CC)
val AtelierDarkInversePrimary = Color(0xFF004743)

val AtelierDarkSecondary = Color(0xFFF4A96E)
val AtelierDarkOnSecondary = Color(0xFF472900)
val AtelierDarkSecondaryContainer = Color(0xFF633E14)
val AtelierDarkOnSecondaryContainer = Color(0xFFFEC394)
val AtelierDarkSecondaryFixed = Color(0xFFFFDCC3)
val AtelierDarkSecondaryFixedDim = Color(0xFFF5BB8C)

val AtelierDarkTertiary = Color(0xFF7CD880)
val AtelierDarkOnTertiary = Color(0xFF00390C)
val AtelierDarkTertiaryContainer = Color(0xFF1D5120)
val AtelierDarkOnTertiaryContainer = Color(0xFFA3D99B)
val AtelierDarkTertiaryFixed = Color(0xFFBAF1B1)
val AtelierDarkTertiaryFixedDim = Color(0xFF9FD497)

val AtelierDarkSurface = Color(0xFF141412)
val AtelierDarkSurfaceBright = Color(0xFF3B3A36)
val AtelierDarkSurfaceDim = Color(0xFF141412)
val AtelierDarkSurfaceVariant = Color(0xFF404945)
val AtelierDarkSurfaceContainerLowest = Color(0xFF0E0E0C)
val AtelierDarkSurfaceContainerLow = Color(0xFF1C1C19)
val AtelierDarkSurfaceContainer = Color(0xFF20201D)
val AtelierDarkSurfaceContainerHigh = Color(0xFF2B2A27)
val AtelierDarkSurfaceContainerHighest = Color(0xFF363532)

val AtelierDarkBackground = Color(0xFF141412)
val AtelierDarkOnBackground = Color(0xFFE6E2DD)
val AtelierDarkOnSurface = Color(0xFFE6E2DD)
val AtelierDarkOnSurfaceVariant = Color(0xFFC0C9C5)
val AtelierDarkInverseSurface = Color(0xFFE6E2DD)
val AtelierDarkInverseOnSurface = Color(0xFF31302D)

val AtelierDarkOutline = Color(0xFF8A9390)
val AtelierDarkOutlineVariant = Color(0xFF404945)
val AtelierDarkSurfaceTint = Color(0xFF7CD4CE)

val AtelierDarkError = Color(0xFFFFB4AB)
val AtelierDarkOnError = Color(0xFF690005)
val AtelierDarkErrorContainer = Color(0xFF93000A)
val AtelierDarkOnErrorContainer = Color(0xFFFFDAD6)
