package com.vishnu.campalette.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF1F5F5B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA6DCD6)
val md_theme_light_onPrimaryContainer = Color(0xFF073432)
val md_theme_light_secondary = Color(0xFF9B6B43)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD8BE)
val md_theme_light_onSecondaryContainer = Color(0xFF3B2210)
val md_theme_light_tertiary = Color(0xFF3E6E3B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E7BD)
val md_theme_light_onTertiaryContainer = Color(0xFF103112)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7F3EE)
val md_theme_light_onBackground = Color(0xFF201B17)
val md_theme_light_surface = Color(0xFFFFFDF9)
val md_theme_light_onSurface = Color(0xFF201B17)
val md_theme_light_surfaceVariant = Color(0xFFE6DDD2)
val md_theme_light_onSurfaceVariant = Color(0xFF4F463D)
val md_theme_light_outline = Color(0xFF8A8076)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF7BC4BD)
val md_theme_dark_onPrimary = Color(0xFF003736)
val md_theme_dark_primaryContainer = Color(0xFF0F4E4B)
val md_theme_dark_onPrimaryContainer = Color(0xFFA6DCD6)
val md_theme_dark_secondary = Color(0xFFE2B083)
val md_theme_dark_onSecondary = Color(0xFF4E2D12)
val md_theme_dark_secondaryContainer = Color(0xFF6A4324)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD8BE)
val md_theme_dark_tertiary = Color(0xFFA8D29F)
val md_theme_dark_onTertiary = Color(0xFF103112)
val md_theme_dark_tertiaryContainer = Color(0xFF294529)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E7BD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF15120F)
val md_theme_dark_onBackground = Color(0xFFECE0D8)
val md_theme_dark_surface = Color(0xFF1A1714)
val md_theme_dark_onSurface = Color(0xFFECE0D8)
val md_theme_dark_surfaceVariant = Color(0xFF3E352E)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C7BC)
val md_theme_dark_outline = Color(0xFF9E9186)
