package com.vishnu.campalette.ui.theme

import androidx.compose.ui.graphics.Color

val AtelierPrimary = Color(0xFF007AFF)
val AtelierOnPrimary = Color(0xFFFFFFFF)
val AtelierPrimaryContainer = Color(0xFFE5F1FF)
val AtelierOnPrimaryContainer = Color(0xFF003E7D)
val AtelierPrimaryFixed = Color(0xFFE5F1FF)
val AtelierPrimaryFixedDim = Color(0xFFB8D8FF)
val AtelierInversePrimary = Color(0xFF64B5FF)

val AtelierSecondary = Color(0xFF5856D6)
val AtelierOnSecondary = Color(0xFFFFFFFF)
val AtelierSecondaryContainer = Color(0xFFE4EBFF)
val AtelierOnSecondaryContainer = Color(0xFF173D9C)
val AtelierSecondaryFixed = Color(0xFFE4EBFF)
val AtelierSecondaryFixedDim = Color(0xFFB9CAFF)

val AtelierTertiary = Color(0xFF6E5AE6)
val AtelierOnTertiary = Color(0xFFFFFFFF)
val AtelierTertiaryContainer = Color(0xFFECE8FF)
val AtelierOnTertiaryContainer = Color(0xFF40328E)
val AtelierTertiaryFixed = Color(0xFFECE8FF)
val AtelierTertiaryFixedDim = Color(0xFFC9BFFF)

val AtelierSurface = Color(0xFFF2F2F7)
val AtelierSurfaceBright = Color(0xFFFFFFFF)
val AtelierSurfaceDim = Color(0xFFD1D1D6)
val AtelierSurfaceVariant = Color(0xFFE5E5EA)
val AtelierSurfaceContainerLowest = Color(0xFFFFFFFF)
val AtelierSurfaceContainerLow = Color(0xFFFFFFFF)
val AtelierSurfaceContainer = Color(0xFFEFEFF4)
val AtelierSurfaceContainerHigh = Color(0xFFE5E5EA)
val AtelierSurfaceContainerHighest = Color(0xFFD1D1D6)

val AtelierBackground = Color(0xFFF2F2F7)
val AtelierOnBackground = Color(0xFF000000)
val AtelierOnSurface = Color(0xFF000000)
val AtelierOnSurfaceVariant = Color(0xFF5F5F65)
val AtelierInverseSurface = Color(0xFF242426)
val AtelierInverseOnSurface = Color(0xFFF7F7F7)

val AtelierOutline = Color(0xFF747478)
val AtelierOutlineVariant = Color(0xFFC6C6C8)
val AtelierSurfaceTint = Color(0xFF007AFF)

val AtelierError = Color(0xFFBA1A1A)
val AtelierOnError = Color(0xFFFFFFFF)
val AtelierErrorContainer = Color(0xFFFFDAD6)
val AtelierOnErrorContainer = Color(0xFF93000A)

val AtelierDarkPrimary = Color(0xFF0A84FF)
val AtelierDarkOnPrimary = Color(0xFF003733)
val AtelierDarkPrimaryContainer = Color(0xFF0A3157)
val AtelierDarkOnPrimaryContainer = Color(0xFFA9D3FF)
val AtelierDarkPrimaryFixed = Color(0xFFB0EEE8)
val AtelierDarkPrimaryFixedDim = Color(0xFF95D2CC)
val AtelierDarkInversePrimary = Color(0xFF004743)

val AtelierDarkSecondary = Color(0xFFF4A96E)
val AtelierDarkOnSecondary = Color(0xFF472900)
val AtelierDarkSecondaryContainer = Color(0xFF633E14)
val AtelierDarkOnSecondaryContainer = Color(0xFFFEC394)
val AtelierDarkSecondaryFixed = Color(0xFFFFDCC3)
val AtelierDarkSecondaryFixedDim = Color(0xFFF5BB8C)

val AtelierDarkTertiary = Color(0xFF7CD880)
val AtelierDarkOnTertiary = Color(0xFF00390C)
val AtelierDarkTertiaryContainer = Color(0xFF1D5120)
val AtelierDarkOnTertiaryContainer = Color(0xFFA3D99B)
val AtelierDarkTertiaryFixed = Color(0xFFBAF1B1)
val AtelierDarkTertiaryFixedDim = Color(0xFF9FD497)

val AtelierDarkSurface = Color(0xFF000000)
val AtelierDarkSurfaceBright = Color(0xFF343437)
val AtelierDarkSurfaceDim = Color(0xFF000000)
val AtelierDarkSurfaceVariant = Color(0xFF29292C)
val AtelierDarkSurfaceContainerLowest = Color(0xFF000000)
val AtelierDarkSurfaceContainerLow = Color(0xFF1C1C1E)
val AtelierDarkSurfaceContainer = Color(0xFF2C2C2E)
val AtelierDarkSurfaceContainerHigh = Color(0xFF3A3A3C)
val AtelierDarkSurfaceContainerHighest = Color(0xFF48484A)

val AtelierDarkBackground = Color(0xFF000000)
val AtelierDarkOnBackground = Color(0xFFF5F5F7)
val AtelierDarkOnSurface = Color(0xFFF5F5F7)
val AtelierDarkOnSurfaceVariant = Color(0xFFB7B7BC)
val AtelierDarkInverseSurface = Color(0xFFE6E2DD)
val AtelierDarkInverseOnSurface = Color(0xFF31302D)

val AtelierDarkOutline = Color(0xFF8A9390)
val AtelierDarkOutlineVariant = Color(0xFF404945)
val AtelierDarkSurfaceTint = Color(0xFF7CD4CE)

val AtelierDarkError = Color(0xFFFFB4AB)
val AtelierDarkOnError = Color(0xFF690005)
val AtelierDarkErrorContainer = Color(0xFF93000A)
val AtelierDarkOnErrorContainer = Color(0xFFFFDAD6)
